// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeat = "seats"

// Seat mapped from table <seats>
type Seat struct {
	ID         string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	ShowTimeID string    `gorm:"column:show_time_id;type:uuid;not null;uniqueIndex:ux_seats_show_time_seat_code,priority:1;index:idx_seats_show_time_status,priority:1" json:"show_time_id"`
	ZoneID     string    `gorm:"column:zone_id;type:uuid;not null" json:"zone_id"`
	SeatCode   string    `gorm:"column:seat_code;type:text;not null;uniqueIndex:ux_seats_show_time_seat_code,priority:2" json:"seat_code"`
	RowLabel   *string   `gorm:"column:row_label;type:text" json:"row_label"`
	SeatNumber *int32    `gorm:"column:seat_number;type:integer" json:"seat_number"`
	Status     string    `gorm:"column:status;type:text;not null;index:idx_seats_show_time_status,priority:2;default:AVAILABLE" json:"status"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName Seat's table name
func (*Seat) TableName() string {
	return TableNameSeat
}
