// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Name      string    `gorm:"column:name;type:text;not null" json:"name"`
	VenueName string    `gorm:"column:venue_name;type:text;not null" json:"venue_name"`
	EventDate time.Time `gorm:"column:event_date;type:timestamp with time zone;not null" json:"event_date"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
