// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameShowTime = "show_times"

// ShowTime mapped from table <show_times>
type ShowTime struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	EventID   string    `gorm:"column:event_id;type:uuid;not null" json:"event_id"`
	Name      string    `gorm:"column:name;type:text;not null" json:"name"`
	StartsAt  time.Time `gorm:"column:starts_at;type:timestamp with time zone;not null" json:"starts_at"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName ShowTime's table name
func (*ShowTime) TableName() string {
	return TableNameShowTime
}
