// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameZone = "zones"

// Zone mapped from table <zones>
type Zone struct {
	ID         string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	ShowTimeID string    `gorm:"column:show_time_id;type:uuid;not null" json:"show_time_id"`
	Code       string    `gorm:"column:code;type:text;not null" json:"code"`
	Name       string    `gorm:"column:name;type:text;not null" json:"name"`
	ZoneType   string    `gorm:"column:zone_type;type:text;not null" json:"zone_type"`
	Capacity   int32     `gorm:"column:capacity;type:integer;not null" json:"capacity"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName Zone's table name
func (*Zone) TableName() string {
	return TableNameZone
}
